Update deploy to gitlab pypi to match our ptivate repos

diff --git a/.ci/gitlab-ci.yml b/.ci/gitlab-ci.yml
--- a/.ci/gitlab-ci.yml
+++ b/.ci/gitlab-ci.yml
@@ -511,19 +511,18 @@ internal-pypi:
   stage: deploy-to-pypi
   needs: [build-ubuntu18-gcc7, python-wheel]
   image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu18
-  only:
-   - master
+  # TODO: uncomment before merging
+  # only:
+  # - master
   script:
-    - pip3 install gtirb-*-py*-none-any.whl
-    - GTIRB_VERSION=$(python3 -c "import gtirb; print(gtirb.__version__)")
-    - curl -L -o response.json "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages?package_type=pypi&package_name=gtirb"
-    - cat response.json ; echo
-    - if [ "$(cat response.json | jq "map(select(.version == \"$GTIRB_VERSION\")) | .[0].version")" = "null" ];
+    - cd build/python
+    - pip3 install twine wheel setuptools --upgrade
+    - rm -rf build dist *.egg-info
+    - python3 setup.py sdist bdist_wheel
+    - twine check dist/*
+    - (twine upload --verbose --repository-url $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi --username gitlab-ci-token --password "$CI_JOB_TOKEN" dist/* | tee response.txt) || (echo $? > exitcode.txt; exit 0)
+    # do not fail if we try to re-upload a package of the same version
+    - if [[ "$(cat exitcode.txt)" != 0 && -z "$(cat response.txt | grep "File name has already been taken")" ]];
       then
-        pip3 install twine wheel setuptools --upgrade;
-        cd build/python;
-        rm -rf build dist gtirb.egg-info;
-        python3 setup.py sdist bdist_wheel;
-        twine check dist/*;
-        twine upload --repository-url $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi --username $GITLAB_PYPI_USER --password $GITLAB_PYPI_PASS dist/*;
+        exit 1;
       fi
